apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-pod-deployment-prueba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-pod
      environment: prueba
  template:
    metadata:
      labels:
        app: mi-pod
        environment: prueba
    spec:
      containers:
      - name: mi-contenedor
        image: nginx:latest
        ports:
        - containerPort: 80
