apiVersion: v1
kind: Service
metadata:
  name: mi-pod-service-produccion
spec:
  selector:
    app: mi-pod
    environment: produccion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
