name: Pipeline de Producción

on:
  push:
    branches:
      - main

jobs:
  produccion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar entorno
      run: echo "::set-env name=ENVIRONMENT::produccion"

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Despliegue en Producción
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && env.ENVIRONMENT == 'produccion' }}
      run: |
        kubectl apply -f deployment-production.yaml
        kubectl apply -f service-production.yaml
